# Generated by Django 6.0.4 on 2026-04-22 19:13

import apps.plants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.plants.models.upload_path),
        ),
    ]
